
name: AutoLintTest

on:
  pull_request:
    branches:
      - "main"
      - "qa"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Linters
        run: docker-compose -f docker-compose.ci.yml run --rm lobby-rate make lint
      - name: Tests/coverage
        run: docker-compose -f docker-compose.ci.yml run --rm lobby-rate make coverage
